Maxime branch -  gazebo_ros2_bolt
stack-of-tasks/ros2_control_bolt pull request #12
Opened 2022-05-16 15:36 UTC by Maxime-Fansi-laas

2022-05-16 15:53 UTC, Maxime-Fansi-laas commented
gazebo_ros2_bolt est inclu dans ros2_control_bolt

2022-05-17 05:21 UTC, olivier-stasse requested changes
Dear Maxime please:
- Remove all the log install build directories
- Avoid to push merge commit where probably a rebase would have been sufficient.
- Please use meaningful title  and description for your PR. "Modification from Maxime" does not tell me what your modification is doing.

2022-05-17 05:21 UTC, olivier-stasse commented on gazebo_ros2_bolt/CHANGELOG.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dear Maxime please remove this file.
It is supposed to be a summary of what are the  changes from a release to another.
If you want to keep it please follow this standard.

2022-05-17 05:21 UTC, olivier-stasse commented on gazebo_ros2_bolt/CMakeLists.txt
> +add_library(gazebo_hardware_plugins SHARED
This library has the same name than the library for the gazebo_ros2_control.
Please change it to gazebo_bolt_hardware_plugins

2022-05-17 05:21 UTC, olivier-stasse commented on gazebo_ros2_bolt/include/install/local_setup.sh
> +# generated from colcon_core/shell/template/prefix.sh.em
Dear Maxime please remove all the install directories and their contents.

2022-05-17 09:38 UTC, Maxime-Fansi-laas commented
Deletion of install, build and log folders.
Deletion of Changelog.rst file.
In CMakeLists.txt, "gazebo_hardware_plugins"    becomes   "gazebo_bolt_hardware_plugins"

2022-05-17 20:23 UTC, olivier-stasse approved these changes

2022-05-17 20:29 UTC, merged